<?php


use EditorLegenda\Legendas\SrtParser;
use PHPUnit\Framework\TestCase;


class SrtParserTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->parser = new SrtParser();
    }

    /**
     * @test
     * @dataProvider parseValidDataProvider
     * @return void
     */
    public function parse(string $legendas)
    {
        $legendasDTO = $this->parser->parse( $legendas );
        $this->assertIsArray( $legendasDTO );
        foreach ($legendasDTO as $index => $l){
            $this->assertIsObject( $l );
        }

    }

    /**
     * @test
     * @dataProvider parseInvalidDataProvider
     * @return void
     */
    public function parseInvalidData($legendas)
    {
        $this->expectException(\EditorLegenda\Exceptions\SrtParserFormatException::class);
        $legendasDTO = $this->parser->parse( $legendas );
    }

    public function parseInvalidDataProvider(): array
    {
        return [
            ["isso não é uma legenda"],
            ["
00:01:33,177 --> 00:01:35,470
<i>♪ Freemont power, Freemont pride ♪</i>"],
            ["1
            sdkfjsfdsf
            fsdhfsjdf"
            ],
        ];
    }

    public function parseValidDataProvider(): array
    {

    $legenda1 = <<<SRT
1
00:01:29,965 --> 00:01:33,093
<i>♪ Freemont pride,
be aggressive, drive, drive, drive ♪</i>
SRT;

    $legenda2 = <<<SRT
2
00:01:33,177 --> 00:01:35,470
<i>♪ Freemont power, Freemont pride ♪</i>

3
00:01:35,554 --> 00:01:37,806
<i>♪ Be aggressive, drive, drive, drive ♪</i>
SRT;


        return [
            [$legenda1,],
            [$legenda2],
        ];
    }

}
